# Generated by Django 4.1.4 on 2022-12-12 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=115)),
                ('first_author_first_name', models.CharField(max_length=20)),
                ('first_author_last_name', models.CharField(max_length=20)),
                ('author_list', models.TextField()),
                ('abstract', models.TextField()),
                ('references', models.CharField(max_length=50)),
                ('laboratory', models.CharField(max_length=50)),
                ('journal_name', models.CharField(max_length=50)),
                ('journal_volume', models.CharField(max_length=10)),
                ('published_date', models.DateTimeField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
