# Generated by Django 4.1.4 on 2022-12-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
